title: Ego Machines
description: A sample Jekyll site
baseurl: /ego-machine-pages
url:  https://markpeatfield.github.io/ego-machine-pages/
plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
